stages:
  - build
  - test
  - deliver
  - deploy

build:
  stage: build
  tags:
    - dev
  script:
    - scripts/docker/build-project.sh
  artifacts:
    paths:
      - "src/*/*/bin"
      - "src/*/*/dist"


test:
  stage: test
  tags:
    - dev
  script:
    - docker run --rm -v=$(pwd):/code -w=/code microsoft/dotnet:2.2-sdk dotnet test -c Release test/AcademyUnitTest/
  dependencies:
    - build
  except:
    - /^v(\d+\.){1,3}\d+$/

deliver-staging:
  stage: deliver
  tags:
    - dev  
  script:
    - scripts/docker/build-image.sh beta
    - scripts/docker/push-image.sh academy-api:beta
    - scripts/docker/push-image.sh academy-spa:beta
    - scripts/docker/push-image.sh academy-web:beta
  dependencies:
    - build
  only:
    - dev

deploy-dev:
  stage: deploy
  tags:
    - staging  
  script:
    - './deploy-development.sh'
  dependencies:
    - build
  only:
    - dev

release-image:
  stage: deliver
  tags:
    - staging  
  script:
    - scripts/docker/build-image.sh ${CI_COMMIT_TAG:-latest}
    - scripts/docker/push-image.sh academy-api:${CI_COMMIT_TAG:-latest}
    - scripts/docker/push-image.sh academy-spa:${CI_COMMIT_TAG:-latest}
    - scripts/docker/push-image.sh academy-web:${CI_COMMIT_TAG:-latest}
  dependencies:
    - build
  only:
    - /^v(\d+\.){1,3}\d+$/

deploy-prod:
  stage: deploy
  tags:
    - prod
  script:
    - ./deploy-production.sh ${CI_COMMIT_TAG}
    - sleep 20
    - 'docker stack ps academy --format "table {{.Name}}\t{{.DesiredState}}\t{{.CurrentState}}\t{{.Error}}" --no-trunc'
  only:
    - /^v(\d+\.){1,3}\d+$/
