version: "3"
services:
  dbserver:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    volumes:
      - "./mssql:/var/opt/mssql"
    command: ["/opt/mssql/bin/sqlservr"]
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Coding-Changes-World
    ports:
      - "1433:1433"
    networks:
      - learning-net
  redis:
    image: redis:alpine
    networks:
      - learning-net
    ports:
      - "6379:6379"
  memcached:
    image: memcached:alpine
    networks:
      - learning-net
    ports:
      - "11211:11211"
  rabbit:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=cnblogs
      - RABBITMQ_DEFAULT_PASS=Coding-Changes-World
    networks:
      - learning-net
    ports:
      - "5672:5672"
  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
    network_mode: "host"
networks:
  learning-net:
